kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr
  labels:
    {{- include "six-lab-basic-bot.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Files.Get "docker-config.json" | b64enc }}
type: kubernetes.io/dockerconfigjson