apiVersion: v1
kind: Service
metadata:
  name: {{ include "six-lab-basic-bot.fullname" . }}
  labels:
    {{- include "six-lab-basic-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "six-lab-basic-bot.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "six-lab-basic-bot.fullname" . }}
spec:
  {{- with .Values.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
 {{- with .Values.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  http:
    - name: "root"
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{ include "six-lab-basic-bot.fullname" . }}
