---
version: 2.1

orbs:
  rust: twdps/rust-api@2.11.0
  cosign: twdps/cosign@0.1.0
  kube: twdps/kube-ops@0.3.0

# ==== global pipeline parameters 

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: cohorts
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file op.env -- /bin/bash -eo pipefail
  registry:
    description: publish to this registry
    type: string
    default: ghcr.io/twks-cohort
  executor-image:
    description: image to use for local jobs
    type: string
    default: twdps/circleci-kube-ops:alpine-0.7.0

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2

  development-build:
    jobs:
      - rust/secure-image-build:
          name: secure-build
          context: << pipeline.parameters.context >>
          shell: /bin/bash
          before-build:
            - run:
                name: inject environment variables
                command: |
                  op inject -i op.env -o $BASH_ENV
                  source $BASH_ENV
                  op inject -i cosign.key.env -o cosign.key
                  op inject -i cosign.pub.env -o cosign.pub
          registry: << pipeline.parameters.registry >>
          image: six-lab-basic-bot
          image-cve-scan: false
          skip-base-image: true
          snyk-organization: twdps
          # health-url: "http://0.0.0.0:8000/v1/teams/healthz"
          port-definition: "8000:8000"
          after-push:
            - cosign/install:
                cosign-version: v2.0.1
            - cosign/sign:
                registry: << pipeline.parameters.registry >>
                image: six-lab-basic-bot
                tag: nonprod.${CIRCLE_SHA1:0:7}
          filters: *on-push-main

  development-deploy-wip:
    jobs:
      - deploy:
          context: << pipeline.parameters.context >>
          name: Deploy to Dev Namespace
          cluster: nonprod-us-east-2
          environment: dev

jobs:
  deploy:
    docker:
      - image: << pipeline.parameters.executor-image >>
    parameters:
      cluster:
        description: target kubernetes cluster
        type: string
      environment:
        description: values environment to use
        type: string
    steps:
      - checkout
      - run:
        name: inject env variables
        command: | 
          op inject -i op.env -o $BASH_ENV
          source $BASH_ENV
      - run:
          name: pull kubeconfig
          command: |
            mkdir -p ~/.kube
            ENV=<< parameters.cluster >> op inject -i tpl/kubeconfig.tpl -o ~/.kube/config
      - run:
          name: Deploy via Helm
          command: |
            helm upgrade \
            --install \
            --namespace team_six-<< parameters.environment >> \
            --values deployment/values-<< parameters.environment >>.yaml \
            --cleanup-on-fail \
            --atomic \
            six-lab-basic-bot \
            ./chart
